language: node_js

sudo: required

env:
  global:
    # Set build specific variables ...
    - CUSTOM_VAR="JACK WAS HERE!"

node_js:
  - node

cache:
  directories:
    - $HOME/.composer/cache

install:
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo add-apt-repository ppa:ondrej/apache2 -y
  - sudo apt-get update
  - sudo apt-get install -y apache2 libapache2-mod-fcgid
  - sudo apt-get install -y php5.6-cli php5.6-cgi php5.6-curl php5.6-gd php5.6-intl php5.6-json php5.6-mcrypt php5.6-mbstring php5.6-mysql php5.6-xml

before_script:
  - test/.travis/before_script.sh
  # - composer self-update
  # - composer install --no-interaction
  # - ./console -v app:install --database-name=suitecrm --database-username=travis --install-admin-username=admin --install-admin-password=admin --install-system-name="SuiteCRM Travis Build" --install-create-database --no-interaction

script:
  - npm test

services:
  - mysql

branches:
  only:
    - master
